plugins {
	id 'java-library'
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'idea'
}

version = mod_version + "+fabric+mc" + minecraft_version
group = mod_group

base {
	archivesName = project.mod_id
}

loom {
	accessWidenerPath = file("src/main/resources/${mod_group}.accesswidener")
}

repositories {
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
	maven {
		// Location of the maven that hosts JEI files since January 2023.
		name = "Jared's maven"
		url = "https://maven.blamejared.com/"
	}
	maven {
		// Location of a maven mirror for JEI files, as a fallback.
		name = "ModMaven"
		url = "https://modmaven.dev"
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	// To change the versions see the gradle.properties file.
	minecraft "com.mojang:minecraft:${minecraft_version}"
	// Fabric loader.
	implementation "net.fabricmc:fabric-loader:${loader_version}"
	// Fabric API.
	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
	// Compile against the JEI API but do not include it at runtime.
	compileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
	// At runtime, use the full JEI jar for Fabric.
	runtimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
}

idea {
	module {
		// Download sources/javadoc jars for dependencies.
		downloadSources = true
		downloadJavadoc = true
	}
}

processResources {
	filesMatching("fabric.mod.json") {
		expand "mod_group": mod_group,
			"mod_id": mod_id,
			"mod_version": mod_version,
			"version": version,
			"minecraft_version": minecraft_version,
			"minecraft_version_range": minecraft_version_range,
			"loader_version": loader_version,
			"fabric_version": fabric_version,
			"jei_version": jei_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
	toolchain.languageVersion = JavaLanguageVersion.of(25)
}

jar {
	from("LICENSE")
	exclude(".cache")
}
